### ISSUE TITLE
allow environment variable to configure queryTimeout

### ISSUE THREAD

**Issue by domdepasquale** [PennState/oracledb_exporter#1]
Allow an allow environment variable to configure queryTimeout  on https://github.com/PennState/oracledb_exporter/blob/master/main.go#L30

Please submit it back to the OG project for a PR.

**Comment by acobaugh** [comment]
https://github.com/iamseth/oracledb_exporter/pull/51

We'll see if they bite. In the meantime I believe we're trying a view for this particular query. Worse comes to worse and we can always amend the chart to allow passing in additional args.

**Comment by domdepasquale** [comment]
Merged https://github.com/iamseth/oracledb_exporter/pull/51
